services:
- type: web
  name: aml-cft-dashboard
  runtime: python
  pythonVersion: "3.8"  # Move this line up, directly under runtime
  buildCommand: "pip install -r requirements.txt"
  startCommand: "gunicorn --bind 0.0.0.0:$PORT app.app:app"
  envVars:
    - key: PYTHON_VERSION
      value: "3.8"
    - key: PYTHONUNBUFFERED
      value: "1"  # Improves logging